services:
      
  website:
    build: .
    container_name: portfolio_app
    ports:
      - "9000:8000"
    volumes:
      - .:/app
      - /home/application_files/portfolio_website/settings.ini:/app/config/settings.ini
      - /home/application_files/portfolio_website/static:/app/static/
    networks:
      - app-network

networks:
  app-network: