services:
      
  db:
    image: mariadb:11
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_pswd
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=
      - NGINX_PORT=80
    depends_on:
      - website

    networks:
      - app-network

  website:
    build: .
    container_name: portfolio_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mariadb_data: